# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config": "00_core.ipynb",
         "download_url": "00_core.ipynb",
         "URLs": "01_url.ipynb",
         "download_data": "01_url.ipynb",
         "file_extract": "01_url.ipynb",
         "newest_folder": "01_url.ipynb",
         "rename_extracted": "01_url.ipynb",
         "FastDownload": "01_url.ipynb"}

modules = ["setup.py",
           "url.py"]

doc_url = "https://fastai.github.io/fastdownload/"

git_url = "https://github.com/fastai/fastdownload/tree/master/"

def custom_doc_links(name): return None
