# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config": "00_helpers.ipynb",
         "download_url": "00_helpers.ipynb",
         "download_data": "00_helpers.ipynb",
         "file_extract": "00_helpers.ipynb",
         "URLs": "01_external.ipynb",
         "FastDownload": "01_external.ipynb"}

modules = ["helper.py",
           "external.py"]

doc_url = "https://fastai.github.io/fastdownload/"

git_url = "https://github.com/fastai/fastdownload/tree/master/"

def custom_doc_links(name): return None
