# AUTOGENERATED! DO NOT EDIT! File to edit: 01_url.ipynb (unless otherwise specified).

__all__ = ['URLs', 'FastDownload']

# Cell
import json
from nbdev.showdoc import *
from fastprogress.fastprogress import progress_bar
from fastcore.all import *
from .helper import *
from .helper import _get_URL

# Cell
URLs = _get_URL()

# Cell
class FastDownload:
    def __init__(self, cfg=None, dir='~/.fastai', archive=None, dest=None, overwrite=False):
        config = Config() if cfg is None else cfg
        data_path = config['data']
        archive_path = config['archive']
        store_attr('data_path, archive_path')

    def download(self, url, dest=None):
        url   = url[0] #FIXME
        fname = Path(url.split('/')[-1])
        fpath = self.archive_path/fname
        dest  = self.data_path/fname.with_suffix('')
        if not dest.exists():
            fpath = download_data(src=url, dest=fpath)
            file_extract(fpath, dest.parent)
        return dest